In [1]:
import numpy as np

In [2]:
A = np.array([[1,2,],[3,4,]])
x = np.array([3,6])      # row vector, 1 dimensional row vector. shape = (2,)
xcol = x[:,np.newaxis]   # explicit conversion to column vector. 2 dimensional matrix, shape = (2,1)
xrow = np.array([x])     # row vector. 2 dimensional matrix, shape = (1,2)

# row vector can be (n,) 1d array or (1,n) 2d array. column vector is (n,1) 2d array
print(f'x = {x}')
print(f'x dim : {x.ndim}, shape : {x.shape}\n')
print(f'x = {xcol}')
print(f'xcol dim : {xcol.ndim}, shape : {xcol.shape}\n')
print(f'x = {xrow}')
print(f'xrow dim : {xrow.ndim}, shape : {xrow.shape}\n')
print('\n')

# Folowing 4 results are same. rowwise multiplication
# [1*3, 2*6; 3*3, 4*6] = [3,12; 9,24]
print(f'{A*x}\n')   # x is treated as a row vector, boradcasts rowwise multiplication
print(f'{x*A}\n')   # x is treated as a row vector, boradcasts rowwise multiplication
print(f'{A*xrow}\n')   # xrow is a row vector, boradcasts rowwise multiplication
print(f'{xrow*A}\n')   # xrow is as a row vector, boradcasts rowwise multiplication
print('\n')

# Folowing 2 results are same. columnwise multiplication
# [1*3, 2*3; 3*6, 4*6] = [3,6; 18,24]
print(f'{A*xcol}\n')
print(f'{xcol*A}\n')
print('\n')

# Matrix vector multiplication
# [1, 2; 3,4]*[3;6] = [15; 33]
print(f'{A@x}\n')     # when on the right side of @, x is implicitly converted to a column vector, results (2, ) array [15, 33]
print(f'{A@xcol}\n')  # same result but the dimension of the output is 2 x 1 array [ [15], [33] ]
#print(f'{A@xrow}\n')  # error, dimension mismatch

# Vector matrix multiplication
# [3,6]*[1, 2; 3,4] = [21, 30]
print(f'{x@A}\n')     # when on the left side of @, x is row vector as it was. results (2, ) array [21, 30]
print(f'{xrow@A}\n')  # same result but the dimension of the output is 1 x 2 array [[21, 30]]
#print(f'{xcol@A}\n')  # error, dimension mismatch



x = [3 6]
x dim : 1, shape : (2,)

x = [[3]
 [6]]
xcol dim : 2, shape : (2, 1)

x = [[3 6]]
xrow dim : 2, shape : (1, 2)



[[ 3 12]
 [ 9 24]]

[[ 3 12]
 [ 9 24]]

[[ 3 12]
 [ 9 24]]

[[ 3 12]
 [ 9 24]]



[[ 3  6]
 [18 24]]

[[ 3  6]
 [18 24]]



[15 33]

[[15]
 [33]]

[21 30]

[[21 30]]

